name: Java CI with Maven (REST and Shell builds)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      ############################
      # REST API build
      ############################
      - name: Build REST API (rest-runner.jar)
        run: |
          mvn clean verify -Prest
          mv target/rest-runner.jar rest-runner.jar

      - name: Upload REST artifact
        uses: actions/upload-artifact@v4
        with:
          name: rest-runner
          path: rest-runner.jar

      ############################
      # Shell CLI build
      ############################
      - name: Build Shell CLI (shell-runner.jar)
        run: |
          mvn clean verify -Pshell
          mv target/shell-runner.jar shell-runner.jar

      - name: Upload Shell artifact
        uses: actions/upload-artifact@v4
        with:
          name: shell-runner
          path: shell-runner.jar

